name: warungku
description: Aplikasi kasir digital untuk warung kelontong/warung makan
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core & Logic
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  
  # Features
  image_picker: ^1.0.7
  mobile_scanner: ^5.0.0
  fl_chart: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.11.1
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/warungku.webp"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
dependency_overrides:
  vector_math: ^2.1.5